### ISSUE TITLE
Video call doesn't work

### ISSUE THREAD

**Issue by fnagel** [meetfranz/recipe-hangouts#8]
It seems video calls are not possible with Franz. Chat works nice but when I try to join a video call (clicking on the green layer on top of a chat window) nothing happens. Any ideas why?

**Comment by diananoias** [comment]
Yes, here two more people with the same issue:
### Hangouts Videocall doesn't open the pop-up window at MeetFranz.
It simply does nothing. It happens in **Mac OS High Sierra** for me.
If you need more information, just ask.
Thanks.

_P.D.: Congratulations for so helpful software you are creating. Thank you._

**Comment by ugtar** [comment]
Same issue on Ubuntu 18.04 (gnome 3.28)

**Comment by fernandofig** [comment]
Happens for me as well (Windows 7 & Windows 10)

To be clear, this isn't quite the same as https://github.com/meetfranz/franz/issues/30 or https://github.com/meetfranz/recipe-hangouts/issues/1 , which were fixed by https://github.com/meetfranz/franz/pull/494 back in the december. That is to say that initiating a Video or Phone call by clicking the buttons at the background of the service DOES work:

![image](https://user-images.githubusercontent.com/1110864/39378678-7ebda722-4a2f-11e8-95a3-969c3954cfb4.png)

What DOES NOT WORK is clicking the video call button on chat windows:

![image](https://user-images.githubusercontent.com/1110864/39378935-22d539e2-4a30-11e8-92bb-0d3f1fbe450f.png)

**Edit:** Forgot to add - I can't receive calls when logged from Franz, as well. I mean, when someone calls me, I'm notified of the call and the "Answer" button shows up, but clicking it won't start the call - it does nothing, just like clicking the button to initiate a call myself doesn't.

**Comment by Lootwig** [comment]
Can confirm, does not work.

**Comment by JeroenSfdc** [comment]
Can confirm same issue. Workaround to use the "Video" call button on the page isn't working as it opens Google Meet instead of Hangout video. Other than that -- I **love** Franz. Productivity!

**Comment by Tazovsky** [comment]
Same issue on MacOS Sierra 10.12.6 (16G1618)

**Comment by eddiemoy** [comment]
This issue is still occuring and has been open for over a year now. It's counterproductive to be using Franz and Hangouts, but also have to then open Hangouts separately in a browser in order to initiate a video call.

**Comment by closingin** [comment]
> This issue is still occuring and has been open for over a year now. It's counterproductive to be using Franz and Hangouts, but also have to then open Hangouts separately in a browser in order to initiate a video call.

Well, Franz is a messaging system at first. This software is built by volunteers and the community, and there are more than 450 issues reported in the main repository right now, so we try to prioritize :slightly_smiling_face: 

We will fix this one when we will be able to do so !
